### ISSUE TITLE
[bug] UTF-8 character width wrongly interpreted

### ISSUE THREAD

**Issue by horriblename** [jakewvincent/mkdnflow.nvim#75]
string length is calculated as the number of bytes, but UTF-8 characters can be more than 1 byte, even though they are really one character when displayed. These characters include many non-English characters (chinese, greek etc.)

table formatting uses string length and causes columns to be wrongly aligned:
![image](https://user-images.githubusercontent.com/59727193/180443543-36abb6f9-f445-4699-97b5-05e76d41cf4c.png)

Solution:
there is no built-in library for handling utf8 in luajit (equivalent to lua 5.1), since the utf8 library was only added in lua 5.4. 

I suggest using [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) `require('plenary').strings.strdisplaywidth`. Many other lua plugins use plenary as well so I think it's fine to have it as a dependency.

Or, you can use [this library](https://github.com/uga-rosa/utf8.nvim) that I found randomly on reddit.

Edit: luautf8 also has `width()`

**Comment by jakewvincent** [comment]
Hi @horriblename, thanks for bringing this up. I feel like when I was writing the table formatting code, I had a thought about len-width mismatches but out of laziness went forward assuming they'd be 1:1. I should be able to get this fixed today or this weekend. Since I already have luautf8 as an optional dependency (for non-ascii to-do symbols), I'll most likely use that library's width function for this.

**Comment by jakewvincent** [comment]
@horriblename I just pushed an update that I think should fix this. You'll need to make sure you have the luautf8 rock installed. (As you probably already know, you can install these via packer by adding `rocks = 'luautf8'` into the table that installs mkdnflow.) Can you try it out and let me know if it works for you?

```lua
use({'jakewvincent/mkdnflow.nvim',
    rocks = 'luautf8',
    config = function()
        require('mkdnflow').setup({})
    end
})
```

**Comment by horriblename** [comment]
Yeah, working flawlessly. Thanks!

**Comment by jakewvincent** [comment]
Excellent :)

**Comment by svenXY** [comment]
Hi, since it was suggested here - I have the mentioned lines in my packer config, luautf8 gets installed successfully, but I still get the following message:

`
⬇️  A to-do symbol is longer than one character or may be a utf8 symbol. To-do functionality may not work as expected. If you wish to use utf8 symbols, install the lua-utf8 luarocks dependency.`

It then works though. 

What can I do to get rid of the error message?

Thanks,
Sven
